### PR TITLE
Allow introspection into probe definition from Ruby

### PR DESCRIPTION
**Pull request by sax**
probe.function => :myfn
probe.name => :probe
probe.arguments => [:string, :integer]

My C is very rusty, so please let me know if you see any issues with this!

### CODE REVIEW

**Comment by sax** [comment]
This is primarily useful for me to write automated tests around probes in libraries I'm trying to instrument.

**Comment by sax** [comment]
@kevinykchan I'm starting to use ruby-usdt on a few projects, and was wondering if you could review this. I'd like to write automated tests around the fact that I send proper arguments to probes, as I've accidentally segfaulted ruby in the past. I don't have a great pattern, but this is a start.

**Comment by thekvn** [comment]
Awesome, very useful.
Thanks @sax.
Pushing new release

**Comment by sax** [comment]
@kevinykchan thank you!

**Pull request merged**
